language: android
dist: trusty

env:
  global:
    - secure: nxUB3eoJhOKO6AfwmhlcA6xZbAKyK2qDG95rkEdkVgA3HSIt7TwysVTXtVIX+t8iu5rkHSXiWtGiStUbhEuh3qFu5K6ifRbk8PQ9BppJwtZt92JrOMLf4N5wzyYQqvAljFuqBxtmyAHVOSp7D4yYx/5W6p8ZS+9u1Os81T6kkK5VcJd+/Ox+Vgb2aYVf5TWSwoIh3USJm4hA+jY7UjT4NXsKTwfBAJ7QgTFjiH7fSPQe99F+STXswQ496ZxRts4/hDmsCJpIeJ3bMJ1mMCoF23LPKZxR9NOcNZcFyo+PvVzfifiojvG//l20L6tamqrdt4pSZNBA11M0ERfBS7MTpFdsGBEoQeQeSepvz/Mo/VlHoHRoxDTbkHNyjOYMwnWzRKJI/Oay0qaBWTeoMNpLoPGKZRtBY4PXxxx3lVBXP5WNb+FaPQju7hdn2INg1VCDBD+axAkj5CPtT5m2npRBHlg2jYfc9tckJ1Ox6f3N+mOI9fPJPAiX+ezvTXY1qBXE94lCNznZNyVBgKe16RkfKAc6LyQXjvZjx72hXXNCuAJoEtGcgckzDQke0zcjLEs+wwdnzURhYhhw6OhfBiYFLAqRcMeSH73EES186wC76jYbvb8q8NFUFO8lO9rUvxLFByPE0udE3XE28YsF2ymhGRBj4yIAMmguRa3oKkW6vX4=
    - secure: i0rtaCj7g7Pp3eCPe/cqHtnUpRE175Xegqq7nQClWiTZlTJE8eNGCy9HdG6438OM/8mrNTnf3x7siAga4gwZhVugGvy49vC0GO1XFsQbj485tX+TDfH7vrep1HO7rWcCAOMr7iIrUcl2I8INa9IorVeh84IsotRDNG6lafTz/wtcTHHJ553Q4qPNgvQfX0dgF7JUviNMbXim5oKHNThForGJT90OC1vtMIgPCmSX8S1O9utJRICWoDXRkx2sQm+OISuhwb+cghmv3N0e3kw5GsmXRjtciTGeVDINftp/m9svn2eWGe+yLk3dgY4n9ztlU3MFFPLnEF+z3L/l5/EJlb2WFOmbmiP6YrObNAPPNObJa7GLg3rB7wkd2EYRFY4qKKiGkuuW1DDG5kC3ncV1QqmA4wL/GcmJd3x/qvKszxLmVnx1Di/9RtjMRuzWl5StCNxdZTZ58Gaf3737MIQUPwG9bnk0XZrDqMTWaWulKgM4Z9dj2foXcFIuimGAi8yBdt9vDXXevcmq7Nz3dtBgmorsXhPgFCCR5Q0ofOXuVhB56mt9Q7IdgutCiQexjM5ycHi2OAlW9DnJqZwvND61gX4VVsDMIXJu4YPXoILH1qs9dnHaVJJkabEtD5PCo/hZi+urhlxB7RnAwCm+6ZheheZPR7etsEX8QW7mtIEHE5M=

android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-28
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

script:
  - "./gradlew ktlintCheck"

before_deploy:
- cp $TRAVIS_BUILD_DIR/hackillinois.keystore $HOME
- cd app/build/outputs/apk/
- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $HOME/hackillinois.keystore -storepass $storepass -keypass $keypass app-release-unsigned.apk key0
- jarsigner -verify app-release-unsigned.apk
- "${ANDROID_HOME}/build-tools/28.0.3/zipalign -v 4 app-release-unsigned.apk hackillinois.apk"
deploy:
  provider: s3
  access_key_id: "$ACCESS_KEY_ID"
  secret_access_key: "$SECRET_ACCESS_KEY"
  bucket: "$DEVELOPMENT_BUCKET"
  skip_cleanup: true
  local_dir: app/build
  on:
    branch: development

before_install:
- openssl aes-256-cbc -K $encrypted_e96e21279759_key -iv $encrypted_e96e21279759_iv -in hackillinois.keystore.enc -out hackillinois.keystore -d
